[package]
name = "fehler"
version = "1.0.0-alpha.0"
authors = ["Without Boats <boats@mozilla.com>"]
edition = "2018"

[dependencies.fehler-macros]
path = "./fehler-macros"
version = "0.1.0-alpha.0"

[workspace]
