[package]
name = "fehler"
version = "1.0.0"
authors = ["Without Boats <boats@mozilla.com>"]
edition = "2018"

[dependencies]
backtrace = "0.3.32"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.fehler-macros]
path = "./fehler-macros"

[workspace]
